name: DevOps Pipeline Validacion

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Instalar dependencias
      run: npm ci --only=dev --ignore-scripts && npm install

    - name: Ejecutar ESLint
      run: npm run lint

    - name: Ejecutar Pruebas Automatizadas
      run: npm test